### PR TITLE
Create ollama_gradio_version.py

### PR DESCRIPTION
**Pull request by Esmail-ibraheem**
Creating gradio version of the project so you have two interface of the ollama chat models using 
1- streamlit AND 
2- Gradio 
image

### CODE REVIEW

**Comment by ayman3000** [comment]
Thanks  @Esmail-ibraheem  for you great contribution. 
Will check it and tell you my feedback.

**Comment by Esmail-ibraheem** [comment]
ok no problem

**Comment by ayman3000** [comment]
Really Great effort..

some notes to enhance:
1- could you show session history as a list instead of a dropdown, so that  users can see other session names easily like the streamlit app or the traditional ChatGPT interface.
2- could you apply the same color theme or whatever you decide (it is just optional).

Thank you very much Eng. @Esmail-ibraheem

**Comment by Esmail-ibraheem** [comment]
ok it's ready now

**Pull request merged**
